/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as ApiRematchRouteImport } from './routes/api/rematch'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'
import { Route as ApiMatchesRouteImport } from './routes/api/matches'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiRapidWebhookRouteImport } from './routes/api/rapid.webhook'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRematchRoute = ApiRematchRouteImport.update({
  id: '/api/rematch',
  path: '/api/rematch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesRoute = ApiMatchesRouteImport.update({
  id: '/api/matches',
  path: '/api/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRapidWebhookRoute = ApiRapidWebhookRouteImport.update({
  id: '/api/rapid/webhook',
  path: '/api/rapid/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai': typeof ApiAiRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/rematch': typeof ApiRematchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/rapid/webhook': typeof ApiRapidWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai': typeof ApiAiRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/rematch': typeof ApiRematchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/rapid/webhook': typeof ApiRapidWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai': typeof ApiAiRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/rematch': typeof ApiRematchRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/rapid/webhook': typeof ApiRapidWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/api/ai'
    | '/api/artifacts'
    | '/api/matches'
    | '/api/onboarding'
    | '/api/rematch'
    | '/session/$sessionId'
    | '/api/rapid/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/api/ai'
    | '/api/artifacts'
    | '/api/matches'
    | '/api/onboarding'
    | '/api/rematch'
    | '/session/$sessionId'
    | '/api/rapid/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/api/ai'
    | '/api/artifacts'
    | '/api/matches'
    | '/api/onboarding'
    | '/api/rematch'
    | '/session/$sessionId'
    | '/api/rapid/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiMatchesRoute: typeof ApiMatchesRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiRematchRoute: typeof ApiRematchRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  ApiRapidWebhookRoute: typeof ApiRapidWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rematch': {
      id: '/api/rematch'
      path: '/api/rematch'
      fullPath: '/api/rematch'
      preLoaderRoute: typeof ApiRematchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches': {
      id: '/api/matches'
      path: '/api/matches'
      fullPath: '/api/matches'
      preLoaderRoute: typeof ApiMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rapid/webhook': {
      id: '/api/rapid/webhook'
      path: '/api/rapid/webhook'
      fullPath: '/api/rapid/webhook'
      preLoaderRoute: typeof ApiRapidWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiRoute: ApiAiRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiMatchesRoute: ApiMatchesRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiRematchRoute: ApiRematchRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  ApiRapidWebhookRoute: ApiRapidWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
